### ISSUE TITLE
Error in app.py

### ISSUE THREAD

**Issue by techstartupexplorer** [TheLime1/AiChatBridge#1]
All has been setup correctly. secrets.ini values are correct

error in executing app.py

Traceback (most recent call last):
  File "/home/socialhelp/AiChatBridge/app.py", line 25, in <module>
    client = PoeApi(tokens)
  File "/home/socialhelp/.local/lib/python3.10/site-packages/poe_api_wrapper/api.py", line 35, in __init__
    raise ValueError("Please provide valid p-b and p-lat cookies")
ValueError: Please provide valid p-b and p-lat cookies

**Comment by diessetechnology** [comment]
Seems to be the error i've fixed tonight. I've sended now the fix as a pull request: #2

**Comment by TheLime1** [comment]
Fixed By #2
